import Head from 'next/head'
import '../styles/globals.css'
import Navbar from './components/Navbar'

function MyApp({ Component, pageProps }) {
  return <main className='main flex text-sm'>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar {...pageProps}/>
    <Component {...pageProps}/>
  </main>
}

export default MyApp
